name: Build and Release

on:
  push:
    tags:
      - 'v*' # åªæœ‰æ¨é€ v å¼€å¤´çš„ tag æ—¶è§¦å‘
      
  workflow_dispatch: # ğŸŒŸ æ–°å¢è¿™ä¸€è¡Œï¼å…è®¸ä½ åœ¨ GitHub ç½‘é¡µä¸Šæ‰‹åŠ¨ç‚¹å‡»æŒ‰é’®æ‰“åŒ…
jobs:
  release:
    runs-on: windows-latest # ä»…ä½¿ç”¨ Windows è™šæ‹Ÿæœº

    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # å»ºè®®ä¿®æ”¹ä¸ºä½ æœ¬åœ°å®é™…ä½¿ç”¨çš„ Node ç‰ˆæœ¬ (å¦‚ 18 æˆ– 20)

      - name: Install Dependencies
        run: npm install

      - name: Publish Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish